// <auto-generated />
namespace MusicTime.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class BlipAjaxTables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BlipAjaxTables));
        
        string IMigrationMetadata.Id
        {
            get { return "202202011838240_BlipAjax-Tables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
